### ISSUE TITLE
Invalid derivation path: m//0

### ISSUE THREAD

**Issue by bitcoineler** [bowstave/meta-writer#5]
**meta-writer --path /fotoalbum/0 "album"** is working
next level (**meta-writer --path /fotoalbum/0/0 "2019"**) gives me an error

```
meta-writer --path /fotoalbum/0/0 "2019"
(node:29180) UnhandledPromiseRejectionWarning: Invalid derivation path: m//0
Error
    at new NodeError (/usr/lib/node_modules/@bowstave/meta-writer/node_modules/bsv/lib/errors/index.js:20:41)
    at HDPrivateKey._deriveFromString (/usr/lib/node_modules/@bowstave/meta-writer/node_modules/bsv/lib/hdprivatekey.js:282:11)
    at HDPrivateKey.deriveChild (/usr/lib/node_modules/@bowstave/meta-writer/node_modules/bsv/lib/hdprivatekey.js:194:17)
    at /usr/lib/node_modules/@bowstave/meta-writer/index.js:230:34
    at Object.<anonymous> (/usr/lib/node_modules/@bowstave/meta-writer/index.js:263:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
(node:29180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by sirdeggen** [comment]
I saw this problem too. Make sure you use latest version? Otherwise there’s an extra forward slash somewhere in the code. Delete it? Also: try `node index.js` rather than `meta-writer`
